### ISSUE TITLE
How to open model in 'Story' app in order to fix camera?

### ISSUE THREAD

**Issue by Antonkl22** [Smithsonian/dpo-voyager#110]
Hello!
Could you tell me, please, how should i open model in 'Story' app in order to fix camera? I have working HTML project with my model, but i can`t understand how to see it in the Story. 

I saw your guide here (https://smithsonian.github.io/dpo-voyager/story/launch/), i copied but nothing changes.

**Comment by gjcope** [comment]
Hi @Antonkl22 ,

Do you have a screenshot? It's hard to help without knowing what is happening.

Voyager Story is a separate component from the Explorer component you are using to view your model. There is a webpage called "voyager-story.html"  in the project package /dist folder that you can launch from whatever webserver you have access to.  Just make sure you have the path to your model folder set correctly as a url parameter such as this: "root=models/your_model/&document=scene.svx.json"

**Comment by gjcope** [comment]
Closing due to lack of follow up. @Antonkl22 feel free to re-open if you are still having issues,
