### ISSUE TITLE
Mobile device- tour stop titles are cut short

### ISSUE THREAD

**Issue by dattoriam** [Smithsonian/dpo-voyager#116]
On mobile devices (tested on google pixel 4a and iphone 11) title text for tour stops is cut off and there is no way see the rest of the text. Switching phone orientation to landscape can help, but issue remains for longer tour titles.

See https://3d.si.edu/object/3d/mammuthus-primigenius-blumbach:341c96cd-f967-4540-8ed1-d3fc56d31f12 

![Image from iOS (5)](https://user-images.githubusercontent.com/59068965/151591910-288a692b-f1a9-42f2-a981-8f58a9278034.png)
![Image from iOS (6)](https://user-images.githubusercontent.com/59068965/151591920-775d1f50-8bc7-47a8-b482-51ee41746bc8.png)

**Comment by gjcope** [comment]
Fixed in v0.31.0 with animated titled on click.
