### ISSUE TITLE
Square highlight behind the round main menu buttons on press (Android Chrome)

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-voyager#117]
Chrome on android shows square highlight behind the round main menu buttons when you press them. (In the video, I'm long pressing the buttons so they don't open the tool)

[example video](https://user-images.githubusercontent.com/49207360/151593426-2c749d26-1aec-4e90-9094-8de08b738f26.mov)
https://user-images.githubusercontent.com/49207360/151593426-2c749d26-1aec-4e90-9094-8de08b738f26.mov

**Comment by gjcope** [comment]
Fixed in #119
