### ISSUE TITLE
"Zoom Extents" centers on scene origin on first click

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-voyager#122]
The "Zoom Extents" button centers on scene origin on first click, and clips the model in the locked view ports  ("Top", "Front", and "left") at the grid (the grid is perpendicular to the camera's view, centered on the origin of the scene.

Pressing the "Zoom Extents" button again will correctly center the model in the plainer views.

Pressing any button (including "Select") or interacting with any of the Explorer view windows/mousing over them will cancel the model clipping.

I like the "Zoom Extents" button as a user as it give me a feeling of control, but using either the "Rotate", "Move", or "Center" tools will perform the same function as the "Zoom Extents" button by centering the model in the view ports. Getting rid of the "Zoom Extents" button could be a easy solution, but as I user I do like that it is there, even if it is a bit superfluous .

**Comment by gjcope** [comment]
Fixed in v0.16.0
