### ISSUE TITLE
Model displays flat black in Voyager, but with correct diffust color in other three.js and babylon.js viewers

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-voyager#123]
![Screen Shot 2022-03-04 at 4 28 38 PM](https://user-images.githubusercontent.com/49207360/156844078-ff6b371b-6332-4159-b9dc-cc92a31065f2.png)
Voyager

![Screen Shot 2022-03-04 at 4 29 34 PM](https://user-images.githubusercontent.com/49207360/156844169-358d793c-2337-44db-b20d-f4fb70c1bc78.png)
https://gltf-viewer.donmccurdy.com/

[Model Link](https://sinet-my.sharepoint.com/:u:/g/personal/blundellj_si_edu/EXg6LQJZjchFoDi23zm28YsBebg5vVz7jzVBbDSs108bKQ?e=TvFH8X)

**Comment by csparker247** [comment]
I just ran across this. In my case, the mesh didn't have surface normals, which are required for the default directional lighting.

**Comment by gjcope** [comment]
Thanks @csparker247 ! You are absolutely right, that model did not have surface normals.

**Comment by gjcope** [comment]
This is fixed in v0.17.0 by supporting the flatShaded attribute.
