### ISSUE TITLE
measure tool issues with some models

### ISSUE THREAD

**Issue by dattoriam** [Smithsonian/dpo-voyager#138]
In some cases, the measure tool applies to the 3D model surface away from where the user clicks. The measure pins can also be off of the 3D model surface and sitting in empty space.

See these models for example of pins being applied to surface away from where the user clicks:
https://3d-api.si.edu/voyager/3d_package:7e4dcb32-b69c-4905-aca5-05c0bea7019d
https://3d-api.si.edu/voyager/3d_package:d017d594-05fe-4d3f-963c-e9c6fcdaaa57

https://user-images.githubusercontent.com/59068965/167711039-2353bca6-f519-4745-9475-80ed831a37d0.mp4

https://user-images.githubusercontent.com/59068965/167711042-28192495-31ad-4611-87e3-f60e3d2d1dac.mp4

See this model for a dramatic example of pins being showing off the surface of the model:
https://3d-api.si.edu/voyager/3d_package:83043304-8a8b-4d49-af51-9ddc323b5c91 
![Screenshot 2022-05-10 14 38 20](https://user-images.githubusercontent.com/59068965/167709541-bc5def71-2913-4f35-8ae5-b01d55fe07c0.png)

See this model for an example of good/desired experience laying down measure pins precisely where the user clicks:
https://3d-api.si.edu/voyager/3d_package:b64f9c0a-3634-4043-9b1d-a2aaf2823317 

https://user-images.githubusercontent.com/59068965/167711095-7916d098-6cf0-41c9-86aa-7d561b1c0c9a.mp4

**Comment by gjcope** [comment]
Fixed in #142
