### ISSUE TITLE
Last measurement taken gets saved to scene file

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-voyager#139]
When authoring in Story, if you use the measure tool, it's state will be saved when saving the scene. This results in seemingly erroneously placed measurement pins when users open the measurement tool. The team discussed this issue and it seems the consensus is that measurement tool state does not need to be included in the initial scene state. Voyager Story should not save the measurement tool state to the scene's initial load state nor should Voyager Explorer try to read the measurement tool's state when first loading a scene.

**Comment by gjcope** [comment]
Fixed in #142
