### ISSUE TITLE
Releasing mouse button click outside of iframe causes buggy navigation

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-voyager#14]
Summary:
Releasing mouse button click outside of iframe causes buggy navigation

Version:
v0.7.5-2-gdec4258

OS/Browser:
Windows 10 and MacOS 10.14
Chrome 80.0.3987.132 (bug does not show up in "Developer Tools" mode), Edge 80.0.361.66 (chromium), Safari 13.0.5

Description:
When Voyager is in an iframe clicking any of the mouse buttons in the iframe to rotate/zoom/pan the model and releasing the click outside of the iframe causes unexpected navigation issues (rotate stuck on, navigation speed might be increased)

Steps to Reproduce:

1. Go to a page with Voyager imbedded in an iframe
https://3d.si.edu/object/3d/triceratops-horridus-marsh-1889:d8c623be-4ebc-11ea-b77f-2e728ce88125

2. Click and hold any mouse button in center of voyager iframe, drag cursor off of iframe, release mouse button

Actual Results:
Performing test with left click or center click will cause that button to appear to be locked on when cursor is over iframe. Subsequent clicks on the iframe will cause further navigation issues
Performing test with right click, then clicking on iframe with any mouse button will cause navigation issues.
Navigation issues include fast rotation/translation and model jumping around viewer

Expected Results:
None, clicking and dragging off iframe should not effect viewer behavior

![image](https://user-images.githubusercontent.com/49207360/76335589-282ad400-62cb-11ea-837f-cc362044cddd.png)

**Comment by gjcope** [comment]
Fixed in #69
