### ISSUE TITLE
Webdev server specs to avoid "Failed to save file" errors?

### ISSUE THREAD

**Issue by apjmason** [Smithsonian/dpo-voyager#141]
Hello, 

Thanks for making this great service available! I'm trying to get it set up on a LAMP server, but having similar issues to those outlined in this [closed issue](https://github.com/Smithsonian/dpo-voyager/issues/27): failed to create or upload errors when trying to save annotations and notes. 

That issue suggests webdav errors. Is there documentation somewhere on what the server specs should be to allow webdav saving by the application? I've looked but am stumped. 

Thanks!

**Comment by apjmason** [comment]
Hi, thanks for the quick response!

I'm using the prebuilt distribution package and did follow those instructions to create the files directory and get the demo assets. I had to change `?root=models/tusk/&document=tusk.svx.json` to `?root=files/models...` to get the tusk to load, and maybe that's the source of my issue? Both `flies` and `models` are 755.

I'm actually getting webdav errors just on loading, I see now, with the final PUT error and notification coming when I try to save. 

Thanks for your help!

![image](https://user-images.githubusercontent.com/10544799/169289177-35e69547-d18a-40ad-9960-adf1a7174d1c.png)

**Comment by gjcope** [comment]
Ah, ok thanks for the clarification. I think I see what is happening. In order for Voyage Story to directly save to disk there needs to be a WebDAV enabled server listening on the port you are connecting to the page through. Then it will respond to any of the client's WebDAV requests. If you deploy Voyager from source (https://smithsonian.github.io/dpo-voyager/introduction/installation/) it will spin up a simple server as well that listens on port 8000 by default. Using the prebuilt you would need to setup and configure your own. It looks pretty straightforward to set this up in Apache (https://www.digitalocean.com/community/tutorials/how-to-configure-webdav-access-with-apache-on-ubuntu-18-04) but unfortunately I don't have any direct experience with that.

It looks like you are using an older version, but if you update to v0.16.0 or higher you also have the option to run Voyager Story in standalone mode which does not require the WebDAV backend to save. Instead it saves the scene package in memory and gives you an option to download it to your local drive.

**Comment by apjmason** [comment]
I just updated to the latest version and see the download option but also still get WebDAV errors when trying to save. How do I enable standalone mode?

I'll try to enable WebDAV on the server if this doesn't work, but figured this might be easiest to try first.

Thanks!

**Comment by gjcope** [comment]
Thanks for the reminder that we still need to update the documentation. :)  To use standalone mode, just set the 'mode' attribute on the component or set it as a url parameter like this: https://your-url.edu/voyager-story-dev.html?mode=standalone

You'll know it worked when you see a yellow box that says 'standalone' in the upper left hand corner like our deployment here: https://3d.si.edu/voyager-story-standalone

**Comment by gjcope** [comment]
And while the documentation is still lacking, we do have a recorded workshop that walks through the functionality here: https://www.youtube.com/watch?v=0TrNgo44Ek4

**Comment by gjcope** [comment]
@apjmason Thanks for following up!

1. In your deployment, were you seeing "Standalone" in a yellow box in the upper left corner? If so, and you were still seeing WebDAV errors, I would definitely like to explore this further as Standalone mode cuts that piece out of the process.

2. We have not seen that article issue on our end. Dragging and dropping images still seems to work. Would you mind opening a separate bug report for this issue? If so, would it also be possible to share your svx file and one of the images you are trying to drag-and-drop?

**Comment by apjmason** [comment]
1. Yes, still getting those errors in standalone mode, and annotations won't display in the Annotation Editor, despite [standalone mode seeming to work](https://3dviewer.sites.carleton.edu/voyager/voyager-story-dev.html?mode=standalone&root=files/models/tusk/&document=tusk.svx.json)
2. Will open a separate report with files

**Comment by gjcope** [comment]
I think I see the issue. We need better documentation and probably some failsafes here. It looks like you are still pointing the browser to a file path ("root="files/..."). In standalone mode you are disconnected from the filesystem. So you need to drag and drop your model into the scene and then add annotations, images to articles, etc.

If change your URI to https://3dviewer.sites.carleton.edu/voyager/voyager-story-dev.html?mode=standalone and drag in content, everything seems to work.

![image](https://user-images.githubusercontent.com/22783547/170771149-19cd42c8-394f-4010-aacb-447c05318ce9.png)

**Comment by apjmason** [comment]
Thanks! That cleaner URL seems to work!

**Comment by gjcope** [comment]
Great! Leaving this issue open for now re: updating documentation and making sure we ignore the 'root' parameter in standalone mode.
