### ISSUE TITLE
Error dragging images into Article Editor on Voyager Story Standalone

### ISSUE THREAD

**Issue by apjmason** [Smithsonian/dpo-voyager#143]
On the [Voyager Story Standalone](https://3d.si.edu/voyager-story-standalone) deployment, I can do everything except add images from the media pane to Article Editor.

When dragging uploaded images into the Article Editor they break with a 404 (NOT FOUND) GET error.  I attach the scene.svx.json and one of the images for testing.

[Img404errorfiles.zip](https://github.com/Smithsonian/dpo-voyager/files/8788896/Img404errorfiles.zip)

**Comment by gjcope** [comment]
@apjmason Are you able to drag images directly into the article editor (no media pane)?

**Comment by apjmason** [comment]
Yes, I am able to drag an image into the Article Editor and it shows up as expected and is saved in the media pane. But when I attempt to drag the same image back from media pane into the Editor again, it still breaks with 404 error.

![image](https://user-images.githubusercontent.com/10544799/170790505-66a33357-a762-47d5-906c-de97dcebb811.png)

**Comment by gjcope** [comment]
Got it, thanks. I will attempt to reproduce this issue and follow up here.

**Comment by gjcope** [comment]
Fixed in release v0.19.0
