### ISSUE TITLE
root attribute does not work as expected when loading a model in voyager-explore

### ISSUE THREAD

**Issue by dirkroorda** [Smithsonian/dpo-voyager#158]
The [documentation](https://smithsonian.github.io/dpo-voyager/explorer/api/) says:

> root: Path to the root folder (base folder for all assets)
> document: Path to the SVX scene descriptor JSON documen to load (relative to the root folder).
> model: URL of a model (supported formats: gltf, glb) to load and display at startup (relative to the root folder)

When I try to embed the voyager in a website by means of the `<voyager-explore>` element with `root`, `model` and `document` attributes, the following works:

```
        rootUrl = "/data/editions/1/3d/4/models/original/"
        model = "clanwilliam.gltf"
        scene = "../../annotations/clanwilliam.json"
```

You would expect that the following would also work:

```
        rootUrl = "/data/editions/1/3d/4/"
        model = "models/original/clanwilliam.gltf"
        scene = "annotations/clanwilliam.json"
```

And it works for the scene: root and scene values are concatenated, but it does not work for the model, the console says:

```
Error: fetch for "http://127.0.0.1:5000/data/editions/1/3d/4/clanwilliam.gltf"
```

Apparently, when voyager constructs the model url it leaves out the `models/original` bit.

This is against the expectations.

I am using `voyager-explorer.min.js` from the [0.21.1 release](https://github.com/Smithsonian/dpo-voyager/releases/tag/v0.21.1).

**Comment by dirkroorda** [comment]
Ah, it might be that the model path is not derived from the model attribute on the `<voyager-explore>` element but from the `uri` in the `assets` in the scene file.

Is the model attribute just a default, to be overridden by the scene file?

**Comment by gjcope** [comment]
Hi @dirkroorda - the intent behind the 'model' attribute was for loading models not specified in the scene file. Our recommended workflow is to include the asset references in the scene file itself. We don't often use the 'model' attribute so it's entirely possible there is an issue. I will take a look.

**Comment by gjcope** [comment]
If you have model references in your scene file as well, I think that's the error you are seeing. Your second example above works for me without the 'document' attribute. I agree the documentation implies that they can/should be used together. I will adjust that. I'm honestly not sure how much utility the 'model', 'geometry', and 'texture' attributes have these days so we may just get rid of them for clarity.

**Comment by dirkroorda** [comment]
Got it. I now load the voyager-explorer with just the document attribute and not the model attribute, and indeed the scene specifies the model to load.
Thanks @gjcope  for the explanation and confirmation. So it is all about documentation on the one hand and me getting in tune with the thinking behind voyager on the other hand.

**Comment by gjcope** [comment]
Yes, definitely a documentation deficiency. I will leave this issue open to make sure it is addressed. Thanks for pointing out the confusion @dirkroorda !

**Comment by gjcope** [comment]
Hi @dirkroorda , I've updated the documentation here: https://smithsonian.github.io/dpo-voyager/explorer/api/ to better address the issue in this thread. I'll close this issue, but feel free to re-open if you feel it needs more clarity in the docs. Thanks!

**Comment by dirkroorda** [comment]
🍦
