### ISSUE TITLE
Voyager-story does not create an article

### ISSUE THREAD

**Issue by dirkroorda** [Smithsonian/dpo-voyager#159]
Here is what I experienced:

I am running voyager-story in a [minimal context](https://github.com/CLARIAH/pure3d/blob/main/docs/pilots/voyager-story-attempt1.md).

In the html I use

```
<voyager-story
      style="position: relative; height: 800px;"
      root="/data/" document="clanwilliam.json">
</voyager-story>
```

The server processes all request urls whose paths start with `/data` as a WebDAV server, and all other requests as a Flask app server. The Flask app serves the static files and the index page on which the voyager element lives.

A lot goes well, WebDAV GET and PUT come through, the scene file is loaded and read correctly, the 3d file is loaded.
In the Voyager Articles list I see the articles.

It goes wrong when I click on an article.

The user facing error panel says: `Failed to create article at 'articles/clanwilliam-house.html'`.

I also cannot create a new article. The message is then `Failed to create article at 'articles/new-article-dfBDFr3GDJso-0.html'`.

But I see the new files appear on the server, with this content: `<h1>New Article</h1>`.

I have tried to find the spot in the code where it goes wrong, and it seems that the following is always involved in these errors: `libs/ff-scene/source/assets/WebDAVProvider.ts`, function `parseResponse()`, and then this specific line:

```
let path = new URL(info.url).pathname;
```

The error is

```
Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid URL
    at WebDAVProvider.parseResponse (WebDAVProvider.ts:242:2)
```

The info.url is "/" and in this case the URL() function fails, because it needs a second argument, the base url.

If I bypass that statement and say

```
let path = info.url
```

there is much more progress, but still the article does not get loaded in the article editor.

**Comment by dirkroorda** [comment]
The statement above that causes errors becomes much better if it is replaced by

```
let path = new URL(info.url, this._rootUrl).pathname;
```

**Comment by dirkroorda** [comment]
But even then, there is other strange behaviour: when I click the `+` for a new article, voyager emits a command to read a new file from the server before it emits a command to write that file to the server. The read fails, but the write succeeds.
Nevertheless, the article does not get loaded.

(I am running the 0.21.1 distribution, but I have sprinkled console.warn() statements in the voyager-story.dev.js, which results in this log:

```
assetReader.getText(articles/new-article-XYKZVRKwaIjc-0.html) end
createEditArticle {article: Article}
createEditArtice start putText {uri: 'articles/new-article-XYKZVRKwaIjc-0.html'}
createEditArticle putText done
```

**Comment by dirkroorda** [comment]
When I click on an existing article, the behaviour is that the original article on disk on the server is replaced by an empty article: the original contents get lost. And the article editor does not open.

The server shows

```
127.0.0.1 - - [03/Sep/2022 17:05:02] "GET /data/articles/clanwilliam-house.html HTTP/1.1" 200 -
127.0.0.1 - - [03/Sep/2022 17:05:02] "PUT /data/articles/clanwilliam-house.html HTTP/1.1" 204 -
127.0.0.1 - - [03/Sep/2022 17:05:02] "PROPFIND /data/ HTTP/1.1" 207 -
```

**Comment by dirkroorda** [comment]
Delving a bit deeper I see this

![assetpaths](https://user-images.githubusercontent.com/1374704/188408961-b0291353-0922-42e5-84c9-79d9c8493ca7.jpg)

So in my setup no article can be found, because the mediamanager indexes the articles by a path that includes a leading `/`, and every article is being looked up by its path without a leading `/`.

Next step: how did that come about?

**Comment by dirkroorda** [comment]
Finally I get an article loaded in the editor, but I had to modify two additional things:

In order to store articles by their relative path:

In `createAssetTree()`:

```
let storePath = decodeURI(info.path)
                  storePath = storePath.startsWith("/") ? storePath.substr(1) : storePath;
                    this._assetsByPath[storePath] = asset;
                    entry.children.push(asset);
```

And to make sure that articles are retrieved by their relative url:

in `getAssetUrl()` of the `CVAssetManager` (not in the `getAssetURL()` of the `CAssetManager`:

```
getAssetUrl(assetPath) {
        const assetPathC = assetPath.startsWith("/") ? assetPath.substr(1) : assetPath;
        const url = new URL(assetPathC, this._baseUrl).href;
      console.warn("getAssetUrl", { assetPath, baseUrl: this._baseUrl, url })
        return this.loadingManager.resolveURL(url);
    }
```

I think the root cause is in the behaviour of the URL() function. The documentation on MDN is less than clear.

When I experiment with it, I get:

```
new URL("foo/bar", "http://xxx/data/")
href: "http://xxx/data/foo/bar"
origin: "http://xxx"
pathname: "/data/foo/bar"
```

This is nice and well, but look at this:

```
new URL("/foo/bar", "http://xxx/data/")
href: "http://xxx/foo/bar"
origin: "http://xxx"
pathname: "/foo/bar"
```

Here the URL() function strips the `data` part from the base url and then attaches the first argument to it.

**Comment by dirkroorda** [comment]
While this hack seems to work for me, I've no idea whether it will break other things!

**Comment by dirkroorda** [comment]
The same problem occurs in other parts of the code, e.g. making a new media folder fails for the same reason.
If I make the path to the new folder relative first, it works.

In `create()` of the `WebDAVProvider

```
parentPath = typeof parentPath === "object" ? parentPath.path : parentPath;
parentPath = parentPath.startsWith("/") ? parentPath.substr(1) : parentPath
```

**Comment by dirkroorda** [comment]
There was an issue in my setup as well. After solving that, it seems everything works OK, except for one issue in the WebDAVProvider code of voyager-story.
I'll write a pull request for that.

The issue at my side was that I have combined an out-of-the-box wsgi webdav server with a custom Flask webapp.
The combination had the effect that url-paths starting with `/data` were relayed to the WebDav server, but the `/data` part got removed from the url-path before it was handled by the webdav server.
So the webdav server thought it was responding to urls like `/articles/clanwilliamhouse.html`, and its responses were based on those stripped paths. 

The second thing was, that the WebDAVProvider in the voyager seems to expect that the urls in the webdav responses are full (with protocol and domain, not the plain url-path).
This is apparent from the code in `parseResponse()`:

```
let path = new URL(info.url).pathname;
```

This code will generate an exception if `info.url` is not a full url.

However, according to the specs of webdav, a server may choose to send back url-paths instead, without the protocol and domain, which is what my wsgi webdav server does.

In order to remedy that, there is an easy fix: replace the line above by

```
let path = new URL(info.url, this._rootUrl).pathname;
```

This works because the WebDAVProvider has stored the full base url when it was initialized as `http://localhost:5000/data`.
The remarkable thing is also that this fix partly overcame my faulty setup: if the webdav server thought it responded
to `articles/xxx.html`, the fixed parseResponse would transform it to `http://localhost:5000/data/articles/xxx.html` first and then to `/data/articles/xxx.html`.

But it worked only partially. If the `info.url` has a value starting with `/`, the URL() constructor works differently, it will *replace* the `data` bit in the root url by the value of the `info.url`, instead of stitching the `info.url` behind the root url.

So a number of things kept going wrong, and I fixed them successively by stripping a leading `/` before applying the URL() function. But that felt increasingly bad.

Because so many things did work, it was only after all this tinkering that I got the idea to modify my setup in such a way that the `/data/` bit did not get stripped before handing the url over to the webdav server.

When I tried that and ran the voyager-story again, I was immediately bitten by that line in the parseResponse function:

```
let path = new URL(info.url).pathname;
```

So I remedied that, and lo and behold: everything else (that I am aware of) works now without additional fixes.

Then I'm left with just one clear issue with the WebDAVProvider: it should accept url-paths in responses and fill them up before reporting them to the rest of the application. Which can be done by passing `this._rootUrl` as second argument to the URL() function.

**Comment by dirkroorda** [comment]
Pull request submitted to the ff-scene repository.

**Comment by dirkroorda** [comment]
Yet there are some remaining quirks.

I have an article with a link to an image like this: `../media/image.png`.

When I load the article in the article editor, everything shows up fine.

Closer inspection reveals that just before the function `writeArticle`, the link has become a full url, like
`http://localhost:5000/webdav/media/image.png`, which is a correct link.

Then `writeArticle` changes the link back into a relative link `media/image.png`.

The point is, this link is relative to the base url, which is `http://localhost:5000/webdav/`, but not relative to the article url, which is `http://localhost:5000/webdav/articles/articlexxx.html`.

Effectively, the `../` is gone.

**Comment by dirkroorda** [comment]
The lesson I take here is: do not use `../` urls. And also: do not use a media folder next to `articles`, but rather inside `articles`. 

Another reason for that is that voyager story does not let you view the folders next to `articles`, even if you have created them from within the voyager.

If you follow the instructions in the voyager-user docs, you will not create those links and sibling media folders, and all goes well.

What is a bit disturbing to me is: there is no real specification of the data organization that the voyager works with.
So how can we know that the current layout will still work in subsequent voyager versions?

If the data layout is not documented, how can the developers produce conversion tools from one version to another?

In the absence of this, it is risky to include the voyager as a pillar in long-term-preservation infrastructure.
To mitigate that risk, we should actively store all voyager versions that have been used to create annotations, and also remmeber which annotations have been created by which versions.

**Comment by gjcope** [comment]
Hi @dirkroorda , thanks for the thorough documentation here. I will review the PR asap.

Regarding the relative links to media, yes this all falls back to the 'root folder' concept as the base for all assets. As you mentioned, using Voyager Story to author this content will insure the links are accurate but I agree that this could be documented better. We welcome any input (or PRs!) on how this could better be communicated.

Another option is to update the conversion to not lose that relative path, if this is important for your use case.

Re: data organization, please see the schemas here: https://github.com/Smithsonian/dpo-voyager/tree/master/source/client/schema - annotations are completely stored within the scene descriptor file which is thoroughly documented and has not changed in some time. If it does, the version will be incremented. Is the main issue here article uri formats?

**Comment by dirkroorda** [comment]
Thanks for the pointers, @gjcope !

**Comment by gjcope** [comment]
Hi @dirkroorda , I've added more description to the documentation in multiple places highlighting the convention for article asset storage. I think this addresses your issue, but if not feel free to reopen with clarification!
