### ISSUE TITLE
Select audio file by drag and drop is broken

### ISSUE THREAD

**Issue by dirkroorda** [Smithsonian/dpo-voyager#161]
In Voyager-Story, Edit mode, I create a new audio element and want to specify the filename by dragging an mp3 file shown in the articles folder to the input control where the filename can be entered.
While dragging everything seems OK, when hovering over the Filename input box, a `+` icon appears, and the input control is marked by a dashed border, but when I drop, the file name does not enter in the input.

There seems to be only one option to achieve the intended effect: manually typing the file name into the box.
And that does work.

I'm using voyager-story (dev), locally built from the latest commit (6363d01faf41a66983a038d78a42104f522a535f), 2022-08-25.
It happens in Chrome and Safari and Firefox.

Some other things I tried and did not help:

* select the tusk
* work with filenames without special characters and spaces

All this happens without errors showing up in the javascript console.

More details of my setup:

* in my local clone of the dpo-voyager repo I added a few mp3 files to `files/models/tusk/articles`, in particular `test.mp3`

```
cd ~/github/Smithsonian/dpo-voyager`
npm start
```

* In the browser I visit http://localhost:8000/voyager-story-dev.html?mode=edit&root=models/tusk/&document=tusk.svx.json

Log from the server:

```
GET /voyager-story-dev.html?mode=edit&root=models/tusk/&document=tusk.svx.json 200 790 - 1.068 ms
GET /fonts/fonts.css 304 - - 0.390 ms
GET /css/voyager-story.dev.css 304 - - 0.188 ms
GET /js/voyager-story.dev.js 304 - - 0.226 ms
GET /models/tusk/tusk.svx.json 200 3239 - 1.451 ms
GET /fonts/HindSiliguri-Regular.woff2 304 - - 0.455 ms
GET /css/voyager-story.dev.css.map 200 176712 - 0.811 ms
PROPFIND /models/tusk/ 207 10042 - 6.202 ms
GET /models/tusk/tusk-20k-512-thumb.glb 200 210260 - 2.689 ms
GET /js/voyager-story.dev.js.map 200 9723682 - 0.684 ms
GET /models/tusk/tusk-200k-4096-high.glb 200 6206540 - 2.684 ms
PROPFIND /models/tusk/articles 207 4635 - 7.026 ms
```

After manually pasting `articles/test.mp3` as file name and pressing Play:

```
GET /models/tusk/articles/test.mp3 206 2 - 5.190 ms
GET /models/tusk/articles/test.mp3 200 213073 - 1.833 ms
```

And the sound plays.

**Comment by gjcope** [comment]
This is issue is fixed in v0.22.0. You can drag mp3 files from the media tab or from your desktop.
