### ISSUE TITLE
'Meta:0' missing from JSON "Scenes" properties

### ISSUE THREAD

**Issue by kgschoueri** [Smithsonian/dpo-voyager#166]
[voyager-scene (1).zip](https://github.com/Smithsonian/dpo-voyager/files/9685056/voyager-scene.1.zip)

The JSON file does not automatically add "meta:0" to the scenes properties. Even when downloading a base json file from the standalone voyager editor, this "meta:0" is missing (see Zip file attached). Was able to manually enter it in the JSON file to get the audio Icon to display in the menu.

**Comment by gjcope** [comment]
Hi @kgschoueri , this issue should be fixed in the v0.23.0 release. The meta object/index should be added any time metadata is included and saved in the SVX file (including audio references). If there is no meta info, the object/index will not be created, which seems correct.
