### ISSUE TITLE
On iOS, releasing touch outside of iframe or on UI element causes buggy navigation

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-voyager#17]
Summary:
On iOS, releasing touch outside of iframe or on UI element causes navigation to get stuck on pan, and jump around

Version:
v0.7.5-2-gdec4258

OS/Browser:
iPhone 7, 13.1.3
- Chrome 80.0.3987.95
- Firefox 23.0 (17297)
- Safari

(Does not effect Chrome or Firefox on up-to-date Android)

Description:
Releasing a touch-and-drag input (to rotate/pan/zoom) on a Voyager UI element (such as tool icon or annotation text box) or outside of an iframe causes unexpected navigation issues (pan stuck on, jumpy navigation, similar but not the same as #14  )

Steps to Reproduce:

1. Go to a page with Voyager
https://3d.si.edu/object/3d/morse-vail-telegraph-key:ed99f44d-3c60-4111-b666-e2908e1b64ef

2.Touch and drag from the center of voyager iframe, release drag on Voyager UI element of off of iframe

Actual Results:
After releasing touch-and-drag on Voyager UI element or outside of iframe will cause all future touch-and-drag inputs to be treated as pan inputs, and will cause jumpy navigation.

Expected Results:
None, where a touch-and-drag input is released should not effect viewer behavior

**Comment by gjcope** [comment]
Fixed in #69
