### ISSUE TITLE
voyager story does not parse webdav responses correctly

### ISSUE THREAD

**Issue by dirkroorda** [Smithsonian/dpo-voyager#172]
A webdav response is a piece of xml using a DAV: namespace. This namespace may or may not be abrreviated by prefix `D:`.

The choice of abbreviation is declared in the xml by means of a namespace map.

However, voyager-story has a hard-wired dependency on `D:` in its code and ignores the namespace mapping.
That occurs in the [parseResponse function](https://github.com/Smithsonian/ff-scene/blob/aef9a32ce3529d586383b68747d25f233a08bd4a/source/assets/WebDAVProvider.ts#L221-L252) in the `ff-scene` repo.

The response is parsed from XML by the xmljs module in this [line](https://github.com/Smithsonian/ff-scene/blob/aef9a32ce3529d586383b68747d25f233a08bd4a/source/assets/WebDAVProvider.ts#L112).

I think you can handle the namespace prefix by calling the xmljs parser with the option `xmlns: true`, by which each element gets extra attributes: the namespace uri and the local name.

By using them, the code will not be dependent on a particular name space prefix, and the webdav client becomes a tad better standards compliant.

**Comment by dirkroorda** [comment]
By the way, I was bitten by this because the python [wsgidav](https://wsgidav.readthedocs.io/en/latest/) webserver that I use did emit the `D:` prefix in its responses, until I integrated it in another backbone, where it suddenly used `ns0:` instead of `D:`, and the whole thing broke.

Yet it is correct to use any arbitrary prefix, if the map between prefix and namespace uri is stated in the xml document, which wsgidav did correctly.

The cause that wsgidav behaved differently turned out to be whether the python module `lxml` is installed on the server or not.

**Comment by dirkroorda** [comment]
I found a fix. Correction to suggestion above: the library used is xml-js, not xmljs, and there is no option `xmlns: true`.
The trick is to strip the namespace prefix here. I'll create a pull-request in ff-scene.

**Comment by gjcope** [comment]
Hi @dirkroorda - thanks for the catch and explanation. Could you make your pull request at https://github.com/Smithsonian/ff-scene/ ? We are working on a branch of that library. Thanks!

**Comment by dirkroorda** [comment]
Done. See https://github.com/Smithsonian/ff-scene/pull/3

**Comment by gjcope** [comment]
@dirkroorda Thanks again for the fix. It has been rolled into v0.23.0 release including the build js package.
