### ISSUE TITLE
Voyager zoom in request

### ISSUE THREAD

**Issue by eriq123** [Smithsonian/dpo-voyager#173]
Can the user zoom in using mouse scroll and have the camera offset (`voyagerElement.getCameraOffset('in')`) changed so that they can still view the 3D object without going beyond the surface on maximum zoom?

**Comment by gjcope** [comment]
Hi @eriq123 , yes definitely. The zoom limits are set on a per-scene basis in the Voyager scene file. You can change this by editing this parameter in the scene file (3rd value of "minOffset" array) or by setting and saving it in the Voyager Story authoring tool.

![image](https://user-images.githubusercontent.com/22783547/201695989-c4253a3d-fdce-4c7f-a785-fe82ad557079.png)

**Comment by gjcope** [comment]
@eriq123 Closing this as I think your question has been addressed. Please reopen if not!
