### ISSUE TITLE
Text in Articles and Annotations Not Copy-able

### ISSUE THREAD

**Issue by kgschoueri** [Smithsonian/dpo-voyager#175]
A user pointed out that text in articles and annotations cannot be copy-pasted. He wished to copy a reference in an article. Is this something that can be enabled by the system?

**Comment by gjcope** [comment]
Hi @kgschoueri I'll need to take another look at this. I know we explicitly disabled this at one point to avoid some issues with interaction on mobile registering as text selection but there may be a better solution.

**Comment by gjcope** [comment]
@kgschoueri we are testing enabling article text selection for this week's release. We have also fixed a bug that previously stopped users from manipulating the model when dragging over an annotation. With that fix in place, selecting text in an annotation would be difficult. Do you think enabling selection in articles alone would work for your users?

**Comment by kgschoueri** [comment]
HI @gjcope yes, I think the ability to select text from an article would be more than enough for our users. Thanks!
