### ISSUE TITLE
Switching models in explorer

### ISSUE THREAD

**Issue by csparker247** [Smithsonian/dpo-voyager#177]
I'm trying to write some custom navigation around Voyager Explorer that allows me to swap out the document being viewed. Previously, my buttons all had `href="?document=foo.json"` attributes, effectively reloading the whole viewer every time. I want to make this a bit more smooth, though, and reuse the page that I already have open.

The way that seems the most obvious is to change the document property on the application:

```javascript
explorer.application.props.document = "foo.json";
explorer.application.evaluateProps();
```

This successfully changes the document, but notably the title does not update with the contents of the new document. Looking through the code for `evaluateProps()`, it occurred to me that I could do it manually but disable document merging:

```javascript
explorer.application.loadDocument("foo.json", false);
explorer.application.postLoadHandler(explorer.props);
```

This causes the title to update and in the dev tools I can see that the correct model path is accessed, but the scene goes black. The tools and overlay buttons all function properly. Clearly there's something about the viewer state here that I don't understand.

I know this isn't part of the official API, so I understand if what I'm trying isn't possible. I can hackily get around this by creating a new `voyager-explorer` element from scratch and replacing the existing one in the DOM, but that seems inelegant and it would be nice to avoid it.

**Comment by csparker247** [comment]
Whoops. I now see that the first option doesn't work as I thought. It's actually loading the new scene into the same rendering context, thus I end up with lots of overlapping models the more times I switch documents.

**Comment by gjcope** [comment]
Hey @csparker247 , you should be able to just switch the component 'root' attribute to point to the path of your new scene (and possibly document if the document name has changed). You can see an example in this Glitch: https://voyager-dev.glitch.me/

**Comment by csparker247** [comment]
Hmm, so that kind of works in that the viewer does attempt to change the scene. It looks like the original document property is being cached, though, and doesn't get changed even when you change the root. My documents are all in a flat directory, but for testing I put them in separate directories like your example, but with unique document names. Then I update like so:

```javascript
explorer.setAttribute('root', 'data/' + doc_dir + '/' + doc);
explorer.setAttribute('document', doc);
```

This results in these loading errors:

<img width="660" alt="errors" src="https://user-images.githubusercontent.com/1434526/208136783-4672cf00-e9f1-4f41-aedd-7cba014ac5c3.png">

The first error is before I've clicked anything, so it's expected to be there. But the other three show the root being updated while the default document name is still being used for loading.

I could rearrange so that everything has a unique directory with an identical document name, but part of the reason I did a flat directory with unique documents was so that the URL parameters were a little more human-readable (e.g. `?document=DocName.json` as opposed to `?document=DocName/document.json`). A quick test suggests that `?root=DocName` doesn't set the property the same way `?document` does.

**Comment by gjcope** [comment]
@csparker247 good point. Our scenes are all set up to use the default document name, so it hadn't come up. It looks like currently we are just reloading based on the 'root' change:
https://github.com/Smithsonian/dpo-voyager/blob/135dd40ec4986b4e73abf19786105395d2e7f18d/source/client/ui/explorer/MainView.ts#L170

Should be easy enough to add 'document' as a driver as well, we will just have to make sure we aren't reloading twice in the case both params are changed.

**Comment by csparker247** [comment]
Sounds good. I'm curious to see if that works given my experience manually setting the document property through Javascript. I'll fork and give it a shot. 

I'm not sure how to handle the case of changing the root and the document at the same time since attributes can only be changed one at a time. But I'll just test the simple `else if` case first.

**Comment by gjcope** [comment]
Thanks, I'm happy to give it a go too but won't happen today.

Attributes can only be changed one at a time, but if the current pattern was used for 'document' and both are changed in succession (as in the example I shared) you would likely end up with the scene being reloaded twice. Not sure how to handle it at the moment either, but I think it's a very real use case.
