### ISSUE TITLE
Circle Annotations Not Following Annotation Tag 

### ISSUE THREAD

**Issue by kgschoueri** [Smithsonian/dpo-voyager#181]
Hi @gjcope, I met today with one of our project partners who decided to use all circle annotations for his project. However, when he made annotation groups using the Tag field. But when trying to enable/disable one or the other groups, all annotations were always visible. Is this a glitch or something specific to the circle annotation type? 

Thanks 

Kelly

**Comment by gjcope** [comment]
Hi @kgschoueri , I don't think we have any examples using circle annotations and annotation groups, so my guess is that it is an uncaught bug. I will investigate.

**Comment by gjcope** [comment]
Fixed in v0.25.0
