### ISSUE TITLE
Deep linking to articles with higlighting of certain strings

### ISSUE THREAD

**Issue by dirkroorda** [Smithsonian/dpo-voyager#192]
For the [pure3D project](https://github.com/CLARIAH/pure3dx) we would like to be able
to deep-link to articles.

The use case is: we want to build a search index over many articles that have been created in Voyager Story for multiple scenes and models.

The question is: how can we make links to the hits, so that when a user clicks such a link, he will be directed to Voyager Explorer displaying the right scene (this is straightforward) but then also with the right article in view (deep linking to articles, currently not in the API as far as I know, after a conversation with @gjcope) and ideally also with certain strings highlighted (the hits, definitely not implemented yet).

So what we want is probably extra attributes by which we can launch the Explorer

```
<voyager-explorer ... deeplink="article:/path/to/article" highlights="dinosaur,trilobite" ...>
```

**Comment by gjcope** [comment]
Hi @dirkroorda - We currently have an [API function that will open an annotation based on id](https://smithsonian.github.io/dpo-voyager/explorer/api-examples/annotations/). A similar function for articles would be quick to add. It could be used in conjunction with the API reader toggle to open the desired article on load. Would this work for the deep-linking piece or would you find needing the id to be prohibitive?

**Comment by dirkroorda** [comment]
@gjcope Good news!

I think that will not be a problem. I just checked.

Suppose a search engine finds a hit in artice `articles/malones-window.html`.

Then we can consult the `scene.svx.json` and look for that article name. That gives

```
 {
          "id": "FD3Rcq8UDenK",
          "uris": {
            "EN": "articles/malones-window.html"
          },
```

There is an id in the neighbourhood. Searching for that ID finds several hits, among with

```
"articleId": "FD3Rcq8UDenK"
```

in the data of an annotation, which confirms this is the article ID.

So, yes, with the scene file in hand, we will find the article ID in which it occurs.

And with your API we can open that article in the reader.

Next question, of course, is: can the hit, or rather the set of hits in that article be highlighted?

At the moment I do not know what search engine we will choose and how it will deliver the hits.

**Comment by gjcope** [comment]
v0.28.0 has a new API function to open articles: https://smithsonian.github.io/dpo-voyager/explorer/api-examples/articles/

I think the highlighting can be implemented outside of Voyager. I did some brief testing and it seems doable, just a little tricky because there is no signal for when the article has finished opening. But maybe we can add support. Will this work for you?

**Comment by gjcope** [comment]
@dirkroorda I'm going to close this issue as we discussed the search/highlighting happening outside of Voyager. If there is any other functionality you think could be helpful for this use case, feel free to reopen.
