### ISSUE TITLE
Images on Annotations: How to

### ISSUE THREAD

**Issue by kgschoueri** [Smithsonian/dpo-voyager#194]
@gjcope, I just tried to put an image on an annotation but I am not successful in getting this to function. Could you write out a workflow for doing this? Does the image have to be a specific file type or file size?

**Comment by gjcope** [comment]
Image support added as of v0.33.0. Images can be dragged/dropped to annotation task pane and credit/caption line and alt text set. The size of the file is not restricted but its display will max out at 120px height, so it's recommended to resize to that or smaller.
