### ISSUE TITLE
Is there an example or demo folder?

### ISSUE THREAD

**Issue by gabrielflorit** [Smithsonian/dpo-voyager#2]
This looks pretty interesting! But I'm not sure how to get started.

**Comment by framelab** [comment]
We're working on documentation as well as adding demo content. Thanks for your patience and please stay tuned!

**Comment by jbaiter** [comment]
I can get the Voyager demo running with docker, but it's missing all of the example data (`tusk`, `ewer` and `chair`)

**Comment by framelab** [comment]
As mentioned above, we're working on updating the documentation and demo content. It's coming!!

**Comment by framelab** [comment]
The latest release, [v0.7.0](https://github.com/Smithsonian/dpo-voyager/releases/tag/v0.7.0) contains demo assets for Voyager. A ZIP file with the assets can be downloaded from the release's asset section. Instructions are provided in the ZIP's `README.txt`. We're also in the process of updating the documentation which can be found [here](https://smithsonian.github.io/dpo-voyager/).
