### ISSUE TITLE
Grabbing explore window as it it is an image

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-voyager#200]
In voyager standalone you can get in a state where clicking and dragging in the in the Explore viewport briefly rotates the models and then drags some elements of the viewport (aspect ratio and scene title) as if they are an image.

To reproduce:
- Clicking and hold outside the view port, on say the task pane
- Drag the pointer into the view port and release. 
- Now any click and drag in the view port results in the odd behavior.
- Clicking outside the view port cancels the odd behavior.

**Comment by gjcope** [comment]
Fixed in v0.28.0 via simple-dropzone fix https://github.com/donmccurdy/simple-dropzone/issues/69

**Comment by gjcope** [comment]
This fix was for the wrong issue! This bug still exists in v0.28.0

**Comment by gjcope** [comment]
Fixed (for real!) in v0.29.0
