### ISSUE TITLE
Articles are submitted as text/plain but text/html is required

### ISSUE THREAD

**Issue by sdumetz** [Smithsonian/dpo-voyager#202]
When an article is created, it is submitted as `Content-Type: text/plain`  by `fetch.text()` (in ff-browser/source/fetch.ts:42) called from `CVAssetWriter.putText()`.

However if the server accepts this content-type and serve it back, it won't show up in `ArticleEditor` when openned, because it only opens on `text/html`:

```
if (event.asset.info.type.startsWith("text/html")) {
  this.openArticle(event.asset.info.path);
} 
```

Obviously I can tweak the server to force `*.html`files to be of type `text/html` but I thought the inconsistent behavior should be reported.

I think it would be better to accept `text/plain`as well as `text/html` (maybe all `text/*` types?) in the previous snippet and/or submit articles as `text/html`

**Comment by gjcope** [comment]
@sdumetz Thanks for pointing out the inconsistent behavior.

On the submit side, I think that is accurate as it is a general purpose function, not tied to articles.

On the read side, are you able to confirm that accepting text/plain does not result in incorrectly rendered output? Just wondering if we need some other validation as the system is handling and expecting html only.

**Comment by sdumetz** [comment]
I made my server send files as `text/plain` with a modified filter in `ui/story/ArticleEditor` and saw no problem.

In fact, tinyMCE content is always set using this line : 

```javascript
tinymce.activeEditor.setContent(content, {format: "raw"});
```

regardless of the content's type.

**Comment by gjcope** [comment]
Thanks for testing. We will update to accept text/* in the next release.

**Comment by gjcope** [comment]
Standardized in v0.28.0
