### ISSUE TITLE
Feature Request: 90-degree snaps

### ISSUE THREAD

**Issue by wolfekat** [Smithsonian/dpo-voyager#207]
It would be helpful to have a keyboard command that quickly rotates a model 90 degrees in the Pose tab of Voyager editor. Sometimes models are aligned to a coordinate system, but have a different axis assigned to the up position. I see that you can type exact degree rotations in the task box, but it could be nice if while rotating a model in the orthographic views, you could hold down a key to make the model "snap" to the closest 90-degree rotation. 

Thank you!

**Comment by gjcope** [comment]
Feature added in v0.36.0 (hold Alt key while rotating)
