### ISSUE TITLE
Share button creates HTML embed code which is percent encoded

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-voyager#21]
The URL (`src="https://3d-api.si.edu/voy...`) in the embed link that voyager creates with the share button is percent encoded which has caused issues with embedding:

HTML snippet created with the share button
`<iframe name="Smithsonian Voyager" src="https%3A%2F%2F3d-api.si.edu%2Fvoyager%2F3d_package%3Ad8c623be-4ebc-11ea-b77f-2e728ce88125" width="800" height="450" allowfullscreen="true"></iframe>`
<img width="1463" alt="Screen Shot 2020-04-09 at 8 49 21 AM" src="https://user-images.githubusercontent.com/49207360/78896927-5a9d2d80-7a3f-11ea-82ec-16d0f0e46e6d.png">

vs what seems to work

`<iframe name="Smithsonian Voyager" src="https://3d-api.si.edu/voyager/3d_package:d8c623be-4ebc-11ea-b77f-2e728ce88125" width="800" height="450" allowfullscreen="true"></iframe>`
<img width="1463" alt="Screen Shot 2020-04-09 at 8 51 06 AM" src="https://user-images.githubusercontent.com/49207360/78896963-6ab50d00-7a3f-11ea-869a-944a3a13f585.png">

I’m not sure of the implications here, but it has caused units trouble when trying to embed voyager.

**Comment by gjcope** [comment]
Fix committed  to main in #23
