### ISSUE TITLE
Tours and measurement feature

### ISSUE THREAD

**Issue by kgschoueri** [Smithsonian/dpo-voyager#213]
When using analysis features during a tour, there doesn't seem to be an elegant way to enable the measurement and analysis tools panels for only one or two steps during a tour. If it is enabled as visible for one step of the tour then it is visible for the entire tour (except when there is an article present in the step). This gets quite busy with four bottom panels visible when it's not always necessary. This seems to be only an issue with the measure tool. Could it be adjusted so that the analysis tool and measurement panel is activated and captured by step rather than by the entire tour? Again, it is necessary specifically for measurement because the measurement panel does show the values in the panel. But when you use slice or other views you can hide the panel, which is good. 

An alternative solution might be to keep the panels hidden but have a pop-up of the measurement values in the Explorer Window.

**Comment by gjcope** [comment]
In v0.38.0 there is now a label directly on the measurement line in the Explorer window.
