### ISSUE TITLE
GLB files corrupting the scene file

### ISSUE THREAD

**Issue by kgschoueri** [Smithsonian/dpo-voyager#233]
Some GLB files when imported into Voyager or soon after present a corruption to the JSON file. For example, null values are replaced in each of the light rotation parameters. This happened on two separate projects. One because of an unsupported advanced texture material and another because of an incorrectly exported GLB file from blender.

**Comment by gjcope** [comment]
Fixed in v0.36.0 - due to no visible models in the scenes on load.
