### ISSUE TITLE
V35.1 Slice Tool malfunction

### ISSUE THREAD

**Issue by kgschoueri** [Smithsonian/dpo-voyager#234]
When enabling the slice tool in some voyager scenes with multiple models, all or certain parts of the models disappear. This happens in V35.1 but not in V.31.0 for the exact same scene file/models. 

**Version 31.0**
<img width="627" alt="V31_Slice" src="https://github.com/Smithsonian/dpo-voyager/assets/107149450/036dc085-dade-42aa-bec5-17bee2076f4e">

**Version 35.1**
<img width="716" alt="V35_Slice" src="https://github.com/Smithsonian/dpo-voyager/assets/107149450/8328826b-c4ea-4495-b0a0-d0514b7f9ebb">

**Version 35.1**
<img width="708" alt="V35_No_Slice" src="https://github.com/Smithsonian/dpo-voyager/assets/107149450/443c5fb6-01a5-47e5-85cc-f32e023efb1f">

**Comment by gjcope** [comment]
Fixed in v0.36.0 - shader update
