### ISSUE TITLE
Wide Images on Annotation Labels appear funky - Extended vs Circle Annotation Styles

### ISSUE THREAD

**Issue by kgschoueri** [Smithsonian/dpo-voyager#236]
For circle annotations, the transparent background of the annotation is limited for wider images, it does not extend with the width of the image. The image hangs over outside the background box. But with the Extended annotation style the image is cropped. 

**Extended Annotation Style**
<img width="862" alt="Extended_wide_photo" src="https://github.com/Smithsonian/dpo-voyager/assets/107149450/056748fd-669d-42b5-b88d-373fe441fcbf">

**Circle Annotation Style**
<img width="1177" alt="Circle_wide_photo_no caption" src="https://github.com/Smithsonian/dpo-voyager/assets/107149450/e85c8612-2d03-41e9-9e24-b6d8f59f7ba9">

**Comment by gjcope** [comment]
Fixed in v0.36.0 - image proportions constrained
