### ISSUE TITLE
Measure Tape during a tour is either on always or off always

### ISSUE THREAD

**Issue by kgschoueri** [Smithsonian/dpo-voyager#238]
The measure tape tool when used in a tour, when it is enabled remains for the rest of the tour. It would be ideal if this can be enabled/disabled under the tour update button.

**Comment by gjcope** [comment]
I believe this is the same as #213 ?

**Comment by kgschoueri** [comment]
It is! We can merge the issues or I can delete this one.

**Comment by gjcope** [comment]
No worries, I will just close this one. #213 is in process!

**Comment by kgschoueri** [comment]
oh nice! 😊
