### ISSUE TITLE
Adjusting the RGB channels for any given light seems to halve the respective lights intensity. 

### ISSUE THREAD

**Issue by campbell-ja** [Smithsonian/dpo-voyager#244]
When editing a voyager scene in voyager story, 

1. load the scene
2. select a light source in the node tree
3. edit any of the RGB channels for said light source
4. that light source will effectively halve its intensity, but the intensity value does not change. so a light at 100% intensity, changes to what is maybe 50% intensity visually. 

5. to fix, re-input the intensity value and the light source will appear correct.

**Comment by gjcope** [comment]
Fixed in v0.37.0
