### ISSUE TITLE
Use the color wheel to select an annotation color

### ISSUE THREAD

**Issue by sdumetz** [Smithsonian/dpo-voyager#257]
Currently annotations color can only be changed by individually tuning R/G/B sliders.

In the properties panel, colors offer a nice shortcut to change them via the color wheel -the `ff-color-button` element- (so much more convenient that individual R/G/B buttons should be entirely hidden IMO).

I wanted to fix it myself, but it turns out both trees relies on different components, namely `ff-property-view` and `sv-property-view` and I wondered if it was some legacy leftovers or if there was a reason for this still, before I start to mindlessly break things?

**Comment by gjcope** [comment]
I think it's just legacy. IMO something sv-property-view based would be preferred to avoid relying on changes to the ff libraries. But I agree the color wheel would be great and am open to whatever solution is the cleanest.

**Comment by sdumetz** [comment]
Ok I'll look into it.

On the matter of the ff-libraries, is there a reason to keep them as submodules instead of including them in the repo? They don't seem to have any relevant external usage?

If possible, this would simplify the some changes (like #250 ) that requires synchronizing multiple submodules.

**Comment by gjcope** [comment]
The new color wheel implementation is included in the latest release (v0.40.1). But user testing noted that, due to browser-specific implementation, the picker displayed on Android Chrome is sub-optimal and significantly different from other experiences. We may need to rethink the custom picker implementation for consistency purposes. Thoughts?

**Comment by sdumetz** [comment]
I have no android device on hand to test this so I can't see it. Do you have a screenshot? Is it on all android flavors?

The native color picker doesn't have a lot of styling options so if it doesn't work well enough on some platforms we will have to bring back a custom one.

I won't be able to work on this before the end of may, but if it's required and you can wait, I suppose I could repurpose the old component into the new system as a starting point?

**Comment by gjcope** [comment]
Initial color picker on Android Chrome:
<img src="https://github.com/Smithsonian/dpo-voyager/assets/22783547/f673894f-9a95-4a9b-a4b1-8307022cf1e3" width="400">
Secondary window through 'More':
<img src="https://github.com/Smithsonian/dpo-voyager/assets/22783547/ff5451b1-a0f8-4e92-af71-d9d84eb49a39" width="400">

I think it can wait. This is still functional I just don't think it fits the goal of consistency. Unless I'm missing some sort of usability aspect of this implementation...

**Comment by gjcope** [comment]
Another issue with this implementation, color inputs are not tab focusable in Safari :( https://bugs.webkit.org/show_bug.cgi?id=194756
