### ISSUE TITLE
Api should enable setting the model quality

### ISSUE THREAD

**Issue by Solcany** [Smithsonian/dpo-voyager#268]
Thank you for this great project.

I'm developing a web app where I show multiple thumbnail-sized viewers in a grid layout. By default all the viewers download the highest available model quality which in the thumbnail preview is unnecessary and creates memory issues. 

If there's currently a workaround to set model quality manually please let me know.

**Comment by gjcope** [comment]
Hi @Solcany ,

Yes, you can use the 'quality' parameter either in the component attributes or url.
https://smithsonian.github.io/dpo-voyager/story/launch/

**Comment by Solcany** [comment]
Thank you @gjcope no idea how I missed that
