### ISSUE TITLE
Failed to create article at 'articles/

### ISSUE THREAD

**Issue by StefSuss** [Smithsonian/dpo-voyager#27]
Hello, great job with the voyager explorer.
We are just taking our first steps with it and are having troubles creating articles. I can create a nex article and it is also created in the models/xxx/articles folder on the server. But trying to edit it via article editor gives me the Failed to create article at 'articles/new-article-q4S0hZR2DUCb.html' error. Where can i look for fixing this?
 THX

**Comment by gjcope** [comment]
Hi, could you provide a little more information and some steps to reproduce the issue? At what point do you get the message? Are you able to see the article in the editor but you get the error when saving? Thanks.

**Comment by benignigiovanni** [comment]
I also have this problem. But also with notes. It seems it is impossible to upload updates to xxx.json files when saving.
Please see attached image.
![image](https://user-images.githubusercontent.com/30176291/89402886-cd7d9300-d717-11ea-8227-e4c30a6eaa02.png)

**Comment by gjcope** [comment]
Hi @benignigiovanni - Can you confirm that there is a file at models/vase/vase.svx.json and check its permissions? If possible, could you also open the developers console (using menu at the upper right of browser) and check for error messages? Thanks.

**Comment by benignigiovanni** [comment]
Permission set to 777
The console returns this error:
voyager-story.min.js:222 PUT http://192.168.115.134/voyager/models/vase/vase.svx.json 405 (Method Not Allowed)
put @ voyager-story.min.js:222
putJSON @ voyager-story.min.js:8
update @ voyager-story.min.js:23
tick @ voyager-story.min.js:32
pulse @ voyager-story.min.js:32
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
requestAnimationFrame (asincrona)
onAnimationFrame @ voyager-story.min.js:32
voyager-story.min.js:222 fetch PUT at 'http://192.168.115.134/voyager/models/vase/vase.svx.json', error: 405 - Method Not Allowed

**Comment by gjcope** [comment]
It looks like there is a WebDAV issue. When you spin up the server is it from an Administrator command prompt? Also, what port do you have the server configured for? It looks like it is not specified in the url.

**Comment by benignigiovanni** [comment]
Thanks gjcope!
Now it's working fine.

Just, in console, I still have a couple of errors when opening an object. Do you have any tip about?
![image](https://user-images.githubusercontent.com/30176291/89497020-c314d500-d7bb-11ea-8ba9-93ddc90be9d7.png)

**Comment by gjcope** [comment]
Glad it's working for you @benignigiovanni - Looks like another WebDAV issue. Are you seeing any issues in the app? Is there anything not loading? I haven't been able to reproduce this issue, but I will look into it and let you know if I find anything.

**Comment by benignigiovanni** [comment]
The only issue I have is with Articles.
When doublc clicking on a new article in the left panel "Articles", I alzays get the error
Error
Failed to create article at 'articles/new-article.html'
but the file exists in the ./articles subdir

Also, the Article Editor in bottom panel is never enabled.
![image](https://user-images.githubusercontent.com/30176291/89529767-8e217600-d7ed-11ea-8c0e-9c004e8e9ab6.png)

Otherwise always is working fine.

N.B. by setting WebDav Allow Property Queries with Infinity Depth as true, the error changes in 
![image](https://user-images.githubusercontent.com/30176291/89529889-d04ab780-d7ed-11ea-8f4f-59777a01e1aa.png)
