### ISSUE TITLE
Floor height depends on capture

### ISSUE THREAD

**Issue by lou-tha** [Smithsonian/dpo-voyager#272]
I have noticed that even when manually changing the height of the floor in the settings, it always jumps to the lowest point of an object, that is used to capture the starting scene.
(I use Voyager with Firefox on a MacBook)

Below are some images to show the floor bug.

Cube is captured for the starting scene, floor has been changed to Y= -2
<img width="716" alt="Cube_Capture" src="https://github.com/Smithsonian/dpo-voyager/assets/62714994/bcde0b95-edf6-43b8-bd5f-5ecc3d40ae4e">

Cube in Voyager Explorer with the floor right beneath the object
<img width="716" alt="Cube_Floor" src="https://github.com/Smithsonian/dpo-voyager/assets/62714994/ee94c741-fb20-46e4-9deb-9504c7aa7595">

Different object, with the height of the object at Y= -2, also used to capture the scene
<img width="716" alt="Sphere_Capture" src="https://github.com/Smithsonian/dpo-voyager/assets/62714994/5d1bc003-ae3a-49fb-9a33-09c8d308e48e">

Cube in Voyager Explorer with the floor lower than the object, sphere was used as scene capture 
<img width="716" alt="Sphere_Floor" src="https://github.com/Smithsonian/dpo-voyager/assets/62714994/2c44fe35-6204-4694-80a7-eef70e705be0">

**Comment by gjcope** [comment]
@lou-tha thanks for the thorough report. We will take a look and follow up here.

**Comment by gjcope** [comment]
@lou-tha Under the Floor settings, there is an an option called 'AutoSize'. Turning this off will allow you to override the autosizing behavior and set your own floor height. There is a bug here though, in that AutoSize currently isn't actually getting saved correctly to the scene file so it will revert to 'true' when you save and reload. This has been fixed and will be in the next release.

**Comment by lou-tha** [comment]
Found the AutoSize option! Thank you for the quick answer and the bug fix

**Comment by gjcope** [comment]
Fixed in v0.41.0
