### ISSUE TITLE
Question: Behavior of Voyager with missing derivatives

### ISSUE THREAD

**Issue by Solcany** [Smithsonian/dpo-voyager#275]
When a derivative corresponding to the specified 'Quality' prop is missing, how does Voyager handle this situation? Does it fall back to a default quality level, or is there error handling that comes into play?

Thank you for your time

**Comment by gjcope** [comment]
Hi @Solcany , it picks the closest available derivative to the desired quality, using the scheme described here: https://github.com/Smithsonian/dpo-voyager/blob/b8d21678cc5c6b68063fa790ff0f7e64ee07b937/source/client/models/DerivativeList.ts#L51

**Comment by Solcany** [comment]
Thank you for your time @gjcope
