### ISSUE TITLE
Viewport windows abruptly minimizing when posing

### ISSUE THREAD

**Issue by wolfekat** [Smithsonian/dpo-voyager#287]
When posing models in Voyager Story, it is possible to fully collapse the vertical or horizontal viewports when quickly releasing on the borders of the viewports. This makes it appears as if some viewports have "disappeared" when they are just minimized. 
<img width="1911" alt="image-2024-6-27_11-14-17" src="https://github.com/Smithsonian/dpo-voyager/assets/131472650/4c316682-5626-41a8-91f7-bc34ca08a858">

**Comment by gjcope** [comment]
Fixed in v0.43.0
