### ISSUE TITLE
Article Reader disappearing

### ISSUE THREAD

**Issue by kgschoueri** [Smithsonian/dpo-voyager#293]
When creating and customising articles in voyager, the article reader disappears entirely when you try to put it to the left or right position in the VScene settings. Returning to overlay view does not resolve the issue. 

https://github.com/user-attachments/assets/143dbb46-501f-4554-95be-efd0984cb357

**Comment by gjcope** [comment]
This regression has been fixed and will be in the next release. Thanks for the bug report @kgschoueri !

**Comment by gjcope** [comment]
Fixed in v0.43.0
