### ISSUE TITLE
Install of Voyager returns errors

### ISSUE THREAD

**Issue by jbresner** [Smithsonian/dpo-voyager#3]
We've recently tried installing the latest Voyager commit following the instructions on the getting-started page and with the latest release, we've run into some problems:

1. After running the git clone command (`git clone --recurse-submodules https://github.com/smithsonian/dpo-voyager .`), the services directory does not contain a `secrets.template.env` file (I think the `config.env` file was also missing). 
2. We tried copying/pasting those files from another instance of voyager on a different  computer but then ended up with these errors after `npm run up`:

```
> voyager@0.7.0 up /Users/jbresner/Library/Mobile Documents/com~apple~CloudDocs/Projects/voyager2
> docker-compose up -d; docker-compose logs -f

WARNING: The VOYAGER_SERVER_PORT variable is not set. Defaulting to a blank string.
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.server.ports is invalid: Invalid port ":", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
WARNING: The VOYAGER_SERVER_PORT variable is not set. Defaulting to a blank string.
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.server.ports is invalid: Invalid port ":", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! voyager@0.7.0 up: `docker-compose up -d; docker-compose logs -f`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the voyager@0.7.0 up script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jbresner/.npm/_logs/2019-11-07T14_22_25_989Z-debug.log
```

We've since got back and checked out commit ac70f89, which is what we last used successfully.

**Comment by vincerossi** [comment]
looking into this now and should have an answer soon

**Comment by framefactory** [comment]
There is a discrepancy between documentation and a recent update. The `config.env` and `secrets.env` files in `/services` no longer exist. They have been replaced by a single `.env` file in the project root.

After cloning the repository, make a copy of the template configuration as follows:
```
cp .env.template .env
```
Then, edit the parameters in the `.env` file (most notably the `VOYAGER_SERVER_PORT` setting).

Apologies for the confusion. I will update the documentation shortly.
