### ISSUE TITLE
obj with normal map

### ISSUE THREAD

**Issue by Malfrik** [Smithsonian/dpo-voyager#30]
Hi,
I have some trouble displaying a Geometry (.obj) with a normal map, as i'm new to normal maps. 
The obj and the regular texture jpg are referenced in the svx.json and are working fine. The normal map is only referenced in the mtl as map_Bump and is not rendered in Voyager-Explorer at the moment. Do I need to reference it in the svx.json as well? And how is it done?

Thx Mal

**Comment by gjcope** [comment]
Hi Mal,

Is there a particular reason that you would like to use .obj? I would recommend converting your file to .glb. This will give you a faster load time and will pack all of the textures and geometry into a single file.

We don't really us .obj currently, but to add the normal map it should just require setting the 'mapType' attribute on the image node in your svx file to 'Normal'.  If this doesn't work for you please let me know and include a copy of your .svx.

Thanks,
Jamie

**Comment by Malfrik** [comment]
Hi gjcope,
you're right .glb would be easy but the texture and details are a lot better with .obj and normals and load time is pretty good in Sketchfab. 
Converting to .glb would be an extra step that costs a lot of extra time, as we need to publish around 600 models in short time. Also .glb puts some weird glitter on the bones, but we are no experts in converting to .glb so perhabs we are missing some step.
I'll test the changes in svx and give you a feedback asap.

**Comment by gjcope** [comment]
There shouldn't be any detail or quality difference between the two formats so yeah there may be an issue with your material setup. You can also try taking a look at our Cook processing framework. It helps you to setup an automated processing pipeline. When automated, converting to .glb takes essentially no time.

**Comment by gjcope** [comment]
Closing this. If you still have questions about syntax for adding an independent normal map, please see #68
