### ISSUE TITLE
annotations come off surface when using keyboard controls

### ISSUE THREAD

**Issue by dattoriam** [Smithsonian/dpo-voyager#300]
If the users zooms in on the model (or pushes part of it off screen) and then uses keyboard controls to go through annotations, the annotations sometimes float out into space. This is self corrected by zooming back out to view the entire model.

![Screenshot 2024-08-29 113014](https://github.com/user-attachments/assets/4a66560b-66aa-4436-9e20-c6794422c37b)
![image (6)](https://github.com/user-attachments/assets/695dab9d-5a5e-4d51-9789-6a20aa40132e)

**Comment by gjcope** [comment]
This is related to default browser accessibility functionality. WCAG standards say anything that is not on screen when focused needs to be, so it gets automatically "scrolled" into view. That's what's happening with the annotations. We can disable this specifically for annotation tabbing, but also needs consideration on how to satisfy the accessibility requirement. This will be on the list for v0.45.0

**Comment by gjcope** [comment]
Closed for now in v0.45.0, but needs alternative accessibility option.
