### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by MIWAR-u** [Smithsonian/dpo-voyager#310]
Hello,

I am currently working on launching an app in a Dockerized environment, but I’ve encountered an issue with the following log output:

voyager-server  |
voyager-server  | up to date, audited 579 packages in 608ms
voyager-server  |
voyager-server  | 92 packages are looking for funding
voyager-server  |   run `npm fund` for details
voyager-server  |
voyager-server  | found 0 vulnerabilities
voyager-server  | npm notice
voyager-server  | npm notice New major version of npm available! 8.19.4 -> 10.8.3
voyager-server  | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.8.3>
voyager-server  | npm notice Run `npm install -g npm@10.8.3` to update!
voyager-server  | npm notice
voyager-server  |
voyager-server  | > voyager@0.44.0 server
voyager-server  | > nodemon services/server/bin/index.js
voyager-server  |
voyager-server  | /usr/bin/env: 'node': Permission denied

Environment details:
Ubuntu 22.04
Docker
Note: Node.js is already installed, and the permissions for node appear to be: -rwxr-xr-x.

I’m wondering how I can fix this issue. Could you please help me resolve this?

I appreciate your assistance and look forward to your response.

Best regards,

**Comment by gjcope** [comment]
What version of Docker are you using? Docker runs containers as root by default, so you may need to change ownership of your app directory.

**Comment by MIWAR-u** [comment]
Thank you for your response. My Docker version is 4.33.1. I'll try the solution.

**Comment by gjcope** [comment]
Apologies for the delay. This has been addressed in v0.46.0. Feel free to reopen if you are still experiencing the same issue.
