### ISSUE TITLE
Camera position improperly linked to CVOrbitnavigation position

### ISSUE THREAD

**Issue by sdumetz** [Smithsonian/dpo-voyager#314]
In the settings tab if I edit the camera's transform, the changes are not propagated to CVOrbitNavigation (and in turn to the CameraController). Which means afterwards if I click to move the camera it will move relative to its old position, which is very much not what I want.

I see many ways this could be fixed but what seems most appropriate to me would be to make the camera's transform read-only to convey the existing fbinding from CVCameraController to CVCamera

We can achieve that using little new code with the existing `linkFrom` and `linkTo` mechanisms, and disable linked properties in the interface.

Is there a more elegant solution I'm not seeing?

**Comment by gjcope** [comment]
Fixed by #315, merged in v0.46.0
