### ISSUE TITLE
SVX differencies to glTF?

### ISSUE THREAD

**Issue by mkoske** [Smithsonian/dpo-voyager#36]
Is there any documentation about what are the differencies between SVX and glTF formats?

**Comment by gjcope** [comment]
Please take a look at: [https://smithsonian.github.io/dpo-voyager/document/]

The svx file is a container for additional scene descriptor information. It has references to any glTF model file to be displayed in the sccene.

**Comment by mkoske** [comment]
So you mean that the SVX is just additional information on top of the glTF format?

**Comment by gjcope** [comment]
Yes exactly. Elements of the scene that are not handled by the glTF spec which focuses on geometry. Things like lights, camera, annotations, etc.
