### ISSUE TITLE
Voyager doesn't load properly in IE 11 or Edge browser

### ISSUE THREAD

**Issue by jbresner** [Smithsonian/dpo-voyager#4]
Both in IE 11 and Edge, the <voyager-explorer></voyager-explorer> tag is empty and nothing is generated inside of it. No messages are displayed in the console indicating any sort of issue. The end result is that Voyager doesn't load or display on the page.

**Comment by framefactory** [comment]
Voyager supports the following browsers:
- Google Chrome, desktop and mobile
- Mozilla Firefox, desktop and mobile
- Apple Safari, OSX and iOS

IE11 is discontinued, and Edge currently doesn't support HTML Custom Elements. Future versions of Edge will support this feature (see https://caniuse.com/#search=custom%20elements).
