### ISSUE TITLE
Offset and scale for annotations is too sensitive

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-voyager#46]
Depending on the scenes units and the size of a model, the offset and scale for annotations can be too sensitive, with values of .01 moving annotations off the screen. This is a particular issue when using the click and scrub method of changing scale and offset.

For example, when changing the scale of a standard or extended annotation using the click and scrub method, moving the mouse less than a millimeter can send the annotation off the screen.

This can be seen in scene 9fb50f36-fd2a-48a2-86d3-50113cc91028 (internal Story location &root=nas2/qc/jwb/9fb50f36-fd2a-48a2-86d3-50113cc91028/)

**Comment by gjcope** [comment]
Addressed in #71
