### ISSUE TITLE
Article editor behavior disconnected from rest of Voyager Story

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-voyager#47]
The article editor currently is not affected by what article or language is selected in either the article task or the Explorer window. This can create confusion for the story author as to what article they are editing. The article editor should behave more like tour editor so it updates based on selected article and language in the task pane/Explorer pane. In this scenario Voyager Story will have to warn users to save before navigating away from an edited article.

**Comment by gjcope** [comment]
Fixed in #104
