### ISSUE TITLE
Unable to add articles or annotations to tours

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-voyager#5]
The tour, annotation, and tool buttons are grayed out during tour creation, so there is no way to incorporate them into tours.

**Comment by framefactory** [comment]
Thanks for pointing this out. This has been fixed now. The buttons for _Annotations_, _Reader_, and _Tools_ remain enabled while editing a tour in Story, but will be disabled while the user consumes a tour in Explorer, to make sure he/she can't mess with the tour state.

The changes will be deployed with the next release (v0.8.0, to be expected in the week of Dec 16).
