### ISSUE TITLE
Title of article in article picker vs HTML article file are not connected

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-voyager#50]
When an article is initialized it takes its title from the title in the article picker (title of the article as listed in the scene.svx) but after the initial creation of the HTML article file the two titles exist separately and updating one does not update the other. It’s not clear what the use case would be for having two different titles for the same article, and feels like if anything it would be confusing. I would recommend Story ensure these titles always agree

**Comment by gjcope** [comment]
Determined to not be an issue. Titles should remain separate so that the article meta data title (entry in article menu) can be different from the article content title (top of html page).
