### ISSUE TITLE
Clicking article button by default opens the first article

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-voyager#52]
It feels like the article view/hide button should probably open to the article picker or there should be explicit way to identify a default article for it to open, ideally with collection record information included (Though this would be Smithsonian specific functionality...)

**Comment by blundellj** [comment]
For an example see the Wiz boots here:
https://3d.si.edu/object/3d/costume-boots-wizard-wiz-broadway-worn-carl-hall:d8c64114-4ebc-11ea-b77f-2e728ce88125

**Comment by gjcope** [comment]
Added in v0.20.0
