### ISSUE TITLE
Assistance after installing prerequisites on a Mac

### ISSUE THREAD

**Issue by srhstevenson** [Smithsonian/dpo-voyager#54]
After installing the prerequisites, where do I then run the necessary commands?

**Comment by gjcope** [comment]
Hi @srhstevenson, I'm not familiar with Macs, but once you have everything installed you will need to open some sort of command prompt or terminal shell window and navigate to the Voyager project directory. Then you will run the npm command listed in the docs to start up your Docker container and build the app. Once your container is running you can also open a bash shell to do manual builds (also described further down in the 'getting started' docs).
