### ISSUE TITLE
Cannot load draco-related files

### ISSUE THREAD

**Issue by mkoske** [Smithsonian/dpo-voyager#55]
If I put e.g. Voyager Mini to "subdirectory", bundled three.js tries to load draco-related files relative to that "subdirectory". How I can configure where these files are fetched?

Subdirectory is in quotes because it's not really a physical directory on the server.

**Comment by gjcope** [comment]
Hi @mkoske,

Please take a look at the 'root'property: https://smithsonian.github.io/dpo-voyager/explorer/usage/
This will allow you to specify the root that files are loaded relative to. It can be set as a component attribute or as a url parameter.

**Comment by mkoske** [comment]
Hi,

I have looked at that page. But I mean draco_wrapper and some draco wasm file.

If I have my page (where I want to use Voyager Mini) at, say http://localhost/some-not-physical-path/1, it tries to load aforementioned files from e.g. http://localhost/some-not-physical-path/js/draco_wrapper.js and cannot find it since that path doesn't exist. 

My Voyager Mini js files are located at e.g. http://localhost/libs/js/voyager.min.js

**Comment by gjcope** [comment]
Ok, sorry wasn't clear to me you were talking about just the Draco files. Yes, they need to be in the relative project folders like they are in our release. If you want to change this you will have to fork the code and take a look at: https://github.com/Smithsonian/dpo-voyager/blob/master/source/client/io/ModelReader.ts where you can modify the path.

**Comment by mkoske** [comment]
Ok, thanks. I have seen that, yes. I just thought maybe it's configurable somehow. 
Is there any specific reason why it must be like this?

**Comment by gjcope** [comment]
No reason that I am aware of. I think it's just an uncommon need that we haven't encountered yet. Feel free to make a feature request or submit a PR. Have you tried it with a logical path? Is everything else working well for you?

**Comment by mkoske** [comment]
Hi! What you mean by logical path? Yes, at least I havent run to any other problems.

**Comment by gjcope** [comment]
@mkoske I mean a path that uses symlinks or routing to resolve the actual file location instead of an existing physical path. Either way, was just wondering if you tried a path that does resolve and if you had any other issues. Thanks for giving it a try!

**Comment by mkoske** [comment]
Hi, I just changed the path in the file you suggested and rebuilt it and it worked. 
Now that I got past that, another thing is that can I somehow use it as a part of a page? I mean that when it's not used so that it covers full page, it still has some layers that covers other controls on the page and thus those other controls (like a menu button) cannot be clicked.

**Comment by mkoske** [comment]
I managed to solve my other issue by just wrapping it inside a div and applying `position: relative` to it, so no need to think about it any more. Thanks!

**Comment by gjcope** [comment]
Glad you figured it out! Please let us know if you have any other questions or issues.

**Comment by mkoske** [comment]
Yea, I will! Thanks for your help. Closing this for now.

**Comment by gjcope** [comment]
Hi @mkoske based on your feedback we've added an option to configure the absolute path to the Draco files through a component attribute or url param called "dracoPath". Included in #69 and current release.

**Comment by mkoske** [comment]
Hi! Thanks a lot!
