### ISSUE TITLE
Long press on iOS causes Voyager frame to be highlighted as text

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-voyager#56]
Tested on an iPhone 7 running iOS 14.4
Issue manifests on up-to-date Chrome, Firefox, and Safari (not present on Android)

Long pressing over a Voyager frame on 3d.si.edu causes the 3D scene to be selected as if it is text.

![IMG_0364](https://user-images.githubusercontent.com/49207360/110978850-e1364b00-8331-11eb-8193-528b5c8c39d0.PNG)

**Comment by gjcope** [comment]
Fixed in #69

**Comment by blundellj** [comment]
![41254BC0-FB63-4B94-92BD-513F2BC4B7ED](https://user-images.githubusercontent.com/49207360/151587498-97629f47-83d3-48ce-bbe3-06241b6a6ac9.jpeg)
![A1E09186-F1AF-4B7A-95D3-16AE7C4CFDB6](https://user-images.githubusercontent.com/49207360/151587503-bf701f43-c72a-4d64-bad9-9084c5ce63b0.png)
![1847D3A1-60FD-4ECE-B745-CD9AAF38A951](https://user-images.githubusercontent.com/49207360/151587511-fe639198-060a-4d88-a8f4-aa7537b7ef0f.png)

**Comment by gjcope** [comment]
Should be fixed in #119
