### ISSUE TITLE
Circle annotations are difficult to open on phone sized moble devices

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-voyager#57]
Tested on
Android: Chrome and Firefox
iOS: Chrome, Firefox, Safari

It can take multiple attempts to get circle style annotations to open on mobile, if at all. In comparison, text annotations are easy to open.

Example: https://3d.si.edu/object/3d/hatch-crew-apollo-11:e7514eea-3f12-490d-a2d0-999f2a1a70f7

**Comment by gjcope** [comment]
Fixed in v0.37.0 with move to HTML based circle annotations.
