### ISSUE TITLE
Expanded annotaion text boxes do not stay within view port at smaller sizes

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-voyager#58]
At smaller fame sizes (especially on mobile, but can manifest on desktop) the expanded annotation text box will be partially out of view. Trying to rotate the model to fit the text box will cause it to move around the sides of the screen, with a section of the text box remaining obscured (this is most prevalent on mobile)

https://user-images.githubusercontent.com/49207360/110982963-29a43780-8337-11eb-9aab-e079f213ebd4.MP4

**Comment by gjcope** [comment]
This should be solved by annotation views and the annotation truncation functionality in v0.39.0
