### ISSUE TITLE
Opening article reader from AR breaks Voyager

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-voyager#60]
Tested on up-to-date Chrome on Android 10
https://3d.si.edu/object/3d/c9ea282c-4bf8-4e8d-9080-750b85f04571

Clicking on the "Read more..." link on an annotation while in AR mode brings up the article viewer at full width of the frame instead of fitting to the right of the UI buttons (so that the UI buttons overlap the article reader)

Closing the article reader then displays an empty Voyager scene and does not bring the user back to the AR view.

![Screenshot_20210312-142510](https://user-images.githubusercontent.com/49207360/110989550-1184e600-8340-11eb-81a1-3ded35a484dc.png)
![Screenshot_20210312-142519](https://user-images.githubusercontent.com/49207360/110989551-121d7c80-8340-11eb-9751-56e1bc54fa02.png)

**Comment by gjcope** [comment]
Fix in #69
