### ISSUE TITLE
Object initially load see though in AR

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-voyager#61]
Tested on up-to-date Chrome on Android 10
https://3d.si.edu/object/3d/c9ea282c-4bf8-4e8d-9080-750b85f04571
https://3d.si.edu/object/3d/rutherford-b-hayes:1f3700e8-6d01-4488-8ab9-ea14031ef641

When viewing a scene in AR, the model initially is semi-transparent so you can see internal geometry and shadows through the model. Issues resolved moving or resizing the model (on drag release)

![Screenshot_20210312-142100](https://user-images.githubusercontent.com/49207360/110989993-b7d0eb80-8340-11eb-9dc8-cf07a6e5f903.png)

**Comment by gjcope** [comment]
This is a Chrome bug (https://bugs.chromium.org/p/chromium/issues/detail?id=1184085) that will hopefully be fixed soon. We will add a temporary path in the next update to fix this for now.

**Comment by gjcope** [comment]
Temporary patch added in #69
