### ISSUE TITLE
How to build document.svx.json file for different file types?

### ISSUE THREAD

**Issue by hamid-eis** [Smithsonian/dpo-voyager#68]
Hey, Can anyone guide me on how to structure the json file for different model file types (obj and gltf). I am using glb with embedded textures but how do I reference texture files of an obj model in json. This is the models section of the json.
`"models": [
    {
      "units": "m",
      "derivatives": [
        {
          "usage": "Web3D",
          "quality": "Thumb",
          "assets": [
            {
              "uri": "trex_thumb.glb",
              "type": "Model"
            }
          ]
        },
        {
          "usage": "Web3D",
          "quality": "Low",
          "assets": [
            {
              "uri": "trex_low.glb",
              "type": "Model"
            }
          ]
        },
        {
          "usage": "Web3D",
          "quality": "Medium",
          "assets": [
            {
              "uri": "trex_medium.glb",
              "type": "Model"
            }
          ]
        },
        {
          "usage": "Web3D",
          "quality": "High",
          "assets": [
            {
              "uri": "trex_high.glb",
              "type": "Model"
            }
          ]
        }
      ]
    }
  ]`

Also the tape tool is not working on my models. When I click on the model the pin randomly appears somewhere else on the model.

**Comment by gjcope** [comment]
Hi @hamid-eis ,
I wouldn't recommend using .obj for web delivery. Glb is really the most efficient solution in this case. But to answer your question, to reference the texture files you would need to add an asset object to the array for that model with type "texture". You can see the schema here: https://github.com/Smithsonian/dpo-voyager/blob/master/source/client/schema/model.ts

Could you open a bug report for the tape tool issue and provide an example model? Thanks!

**Comment by hamid-eis** [comment]
Hi @gjcope ,
Can you share a json file with me for this OBJ model.
[mobj.zip](https://github.com/Smithsonian/dpo-voyager/files/6295299/mobj.zip)
I have tried adding texture files in the assets array with "type: Texture" but I can't get it to work.
This is the error:
`Failed to load model derivative: SyntaxError: Unexpected token # in JSON at position 0.`

**Comment by gjcope** [comment]
Sure, here is an example of the derivative section for the model you shared:

```
"derivatives": [
      {
          "usage": "Web3D",
          "quality": "Low",
          "assets": [
              {
                  "uri": "woo02.obj",
                  "type": "Geometry"
              },
              {
                  "uri": "Image_1.jpg",
                  "type": "Image",
                  "mapType": "Color"
              },
              {
                  "uri": "Image_0.jpg",
                  "type": "Image",
                  "mapType": "Normal"
              }
          ]
      }
]
```

Though I would still recommend using a .glb for something like this.

**Comment by hamid-eis** [comment]
I was using type Model and Texture instead of Geometry and Image. I will try to use .glb in future. Thank you

**Comment by gjcope** [comment]
Great! Closing this then. Please let us know if you have any other issues.
