### ISSUE TITLE
Tape Tool not working properly on my model

### ISSUE THREAD

**Issue by hamid-eis** [Smithsonian/dpo-voyager#70]
#### Steps to reproduce 
1. Load this model in voyager explorer
[trex_medium.zip](https://github.com/Smithsonian/dpo-voyager/files/6271879/trex_medium.zip)

2. Try to use tape tool to measure 

#### Current behavior (bug)
Measure pins are not placed correctly on the model. They spawn randomly on canvas.

#### Expected behavior (correct)
Pins should be placed where the mouse pointer is.

[Bug](https://user-images.githubusercontent.com/73230974/113873756-87a92b00-97ce-11eb-801b-6707d442d0cb.png)

/label ~Bug

**Comment by gjcope** [comment]
Hey @hamid-eis took a look at your file. We aren't currently accurately supporting all the different types of picking (measuring, annotations) when loading a file with multiple meshes with different transformation paths. This is on the roadmap to support but I don't have an delivery estimate. If you are open to restructuring your file to get it to work, let me know.

**Comment by hamid-eis** [comment]
Yeah sure I can restructure my files. Can you guide me on how to structure the file for it to work perfectly?

**Comment by gjcope** [comment]
The quickest way would be to flatten the file (collapse the transforms into the meshes). There should be a quick way to so it before export in whatever modeling software you use. If you use Blender you can do it with Apply (https://docs.blender.org/manual/en/latest/scene_layout/object/editing/apply.html)

**Comment by hamid-eis** [comment]
Thank you this worked for me.

**Comment by gjcope** [comment]
Hi @hamid-eis we fixed this functionality in commit #71 and the current release so it will now work with your original file as well.
