### ISSUE TITLE
Alpha/Transparency not showing

### ISSUE THREAD

**Issue by hamid-eis** [Smithsonian/dpo-voyager#76]
I am using a glb model with alpha/transparency in it but it is not showing in the model.

**Comment by gjcope** [comment]
Hi @hamid-eis are you able to share an example model? We do have alpha support (an example is here: https://3d.si.edu/object/3d/cassiopeia-supernova-remnant:d8c64e02-4ebc-11ea-b77f-2e728ce88125) so it would be helpful to troubleshoot.

**Comment by hamid-eis** [comment]
I am using this model.
[alphamodel.zip](https://github.com/Smithsonian/dpo-voyager/files/6530265/alphamodel.zip)

**Comment by gjcope** [comment]
Hi @hamid-eis sorry for the delay. It looks like the object opacity is overriding the texture alpha. If I set it to anything less than 1 the alpha shows up. I will fix this in an upcoming release and let you know here.

**Comment by hamid-eis** [comment]
Hi @gjcope, no problem and thank you.

**Comment by gjcope** [comment]
Hi @hamid-eis support for this has been added in the most recent release.
