### ISSUE TITLE
Exposure slider does not change scene/model brightness

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-voyager#87]
Steps to reproduce:
- Open a scene in Voyager Story
- Select the Scene node using the Navigator pane
- Select the Settings tab from the ribbon at the top of the page
- In the task pane go to View>Render>Exposure
- Side/change the Exposure value

Expected results:
The scene should change brightness relative to the Exposure value

Current results:
The Exposure value does not seem to do anything

![Screen Shot 2021-08-17 at 10 49 50 AM](https://user-images.githubusercontent.com/49207360/129748782-8fe49841-eb8d-40ca-bb80-0a2c4c1cc45c.png)

**Comment by gjcope** [comment]
This is because exposure is a property of tone mapping which is turned off by default. I've added a field toggle it on and off with a hard-coded tone mapping type (https://64.github.io/tonemapping/#aces) on the back end.

**Comment by gjcope** [comment]
Fixed in #104
