### ISSUE TITLE
Position of lights do not scale with scene

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-voyager#88]
Lights do not scale to fit around the model, so if a model is very large, all of the lights will appear to be inside the center of the model. Theoretically if a model was very small, the lights would also be very far away, but I have not really run into this.

This makes the lights hard to position and also causes unideal lighting if a model does not fit within the existing lighting set up.
![Screen Shot 2021-08-17 at 11 02 48 AM](https://user-images.githubusercontent.com/49207360/129750848-8e91b237-68d4-413e-a582-9051aef3b177.png)

**Comment by gjcope** [comment]
Fixed in v0.28.0
