### ISSUE TITLE
Annotations cluttered if open when WebXR AR mode initializes

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-voyager#92]
If annotations are open when you start WebXR AR mode, they cluster up in the center of the screen until the 3D model loads

Might be related to #65

https://user-images.githubusercontent.com/49207360/133301094-c76e69fe-88ca-4213-a97c-50ee8ab7473b.MOV

**Comment by gjcope** [comment]
Patched in #142 by hiding annotations until object placement.
