### ISSUE TITLE
Articles are only have left hand padding on mobile (overlay mode) 

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-voyager#94]
Article padding on mobile (overlay mode) only has padding on the left of the article which is a little disorienting and for some images makes it unclear if part of the image it being clipped (It does not seem to be clipped, but it unclear to me and to a normal user they might think an image is being clipped even if it is not)

Mobile
<img width="375" alt="ios_left_hand_padding" src="https://user-images.githubusercontent.com/49207360/133304194-fff63c7c-fafc-4082-aacf-6cac57d2271b.png">

Desktop (tweaked background color to show article pane better)
![Desktop](https://user-images.githubusercontent.com/49207360/133304692-5aaaf0f3-034d-467c-8b10-cb41ab7460aa.png)

**Comment by gjcope** [comment]
Fixed in #104
