### ISSUE TITLE
Wide extended annotation box on initial open and every close

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-voyager#96]
For models with extended annotations, the first time annotations are turned on after loading the scene (by selecting the speech bubble icon on the left hand side of the Voyager window), all annotation boxes all momentarily are extremely wide then snap down to there normal size. Turning annotations off and on will not cause this to happen again until the entire scene is reloaded.

(^is this related to the issue where circle annotations briefly load at a different size before popping in at the correct size?)

Once annotations are turned, on closing an opened extended annotation (by clicking off the annotation or on a different annotation) will cause it to momentarily become wider than normal before it returns to it expected closed size. 

https://user-images.githubusercontent.com/49207360/133311045-a11286d1-30ec-4d4d-81bc-9992b3581c26.mov

**Comment by gjcope** [comment]
Fixed in #104
