### ISSUE TITLE
Mobile preview/overlay in story mode for Tour authoring

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-voyager#97]
Most tours are authored in a landscape oriented screen (on a desktop computer), but might be consumed on a device in landscape or portrait orientation. Because of how Voyager resizes, in portrait mode the right and left sides of a view might be clipped. A way to address this issue could be to include an overlay on the Explorer window in Story while authoring tours that indicates how the current view will be displayed on a portrait oriented screen. Another option could be a mobile preview button.

This ticket relates to "Views during a tour can be clip when in portrait aspect ratio" #98

For an example see tour stop 4 on the Roberto Clemente's Batting Helmet scene
https://3d.si.edu/object/3d/roberto-clementes-batting-helmet:92c986d0-2b8d-43c1-8354-e9a2e80d0f9e

![example](https://user-images.githubusercontent.com/49207360/133456103-62bcaf87-6a24-45e8-8289-f75796ce0077.png)

**Comment by gjcope** [comment]
Added as aspect ratio toolbar in v0.22.0
