### ISSUE TITLE
Frame annotation within view when it is clicked on/opened

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-voyager#99]
Some times it is hard to get an annotation within the field of view of a Voyager window. To address this issue it could be nice if when you click on an annotation it centers the point of interest in the center of the Voyager window and makes sure the annotation is fully viewable (not clipped by the edge of the window).

A simple way to achieve keeping the annotation text on screen (at least left to right wise) would be to set a maximum annotation box width of 1/3 of the voyager window size.

**Comment by gjcope** [comment]
This should be solved by annotation views and the annotation truncation functionality in v0.39.0
